target-version = "py311"
line-length = 100

[lint]
select = ["E", "F", "I"]  # PEP8, pyflakes, import sort
# 필요하면 ignore 추가

[lint.per-file-ignores]
"create_db.py" = ["F401"]
"kjh_nanophotonics_portfolio/kjh_nanophotonics_portfolio.py" = ["F401"]