FROM python:3.12 AS builder

ARG BUILD_DATABASE_URL
ENV DATABASE_URL=${BUILD_DATABASE_URL}
ARG REFLEX_API_URL
ENV REFLEX_API_URL=${REFLEX_API_URL}

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
RUN reflex export --frontend-only --no-zip

FROM nginx:1.21-alpine

# 빌더 스테이지에서 생성된 정적 파일들을 Nginx의 기본 웹 루트로 복사
COPY --from=builder /app/.web/build/client /usr/share/nginx/html
# 우리가 직접 작성할 Nginx 설정 파일 복사
COPY ./nginx.conf /etc/nginx/conf/d/default.conf