FROM python:3.12 AS builder

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
ARG REFLEX_API_URL
ENV REFLEX_API_URL=${REFLEX_API_URL}

WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
RUN reflex export --frontend-only --no-zip

RUN ls -laR /app

FROM nginx

COPY --from=builder /app/.web/build/client /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf