# Dockerfile.backend
FROM python:3.12-slim-bullseye

ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN apt-get update && \
    apt-get install -y unzip curl --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

# backend 서버만 실행
CMD ["reflex", "run", "--env", "prod", "--backend-only"]