FROM python:3.12

# 앱 실행에 필요한 환경 변수
ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

# backend.zip을 풀고 uvicorn으로 백엔드 서버만 실행
CMD bash -c "unzip -o backend.zip && uvicorn kjh_nanophotonics_portfolio.kjh_nanophotonics_portfolio:app --host 0.0.0.0 --port 8000"