name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: portfolio-deploy
  cancel-in-progress: true

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Python 설정 + 품질검사/테스트(커버리지 100% 기준은 예시)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov ruff mypy

      - name: Lint (ruff)
        run: ruff check .

      - name: Type check (mypy)
        run: mypy .

      - name: Test (cov=100)
        run: pytest --maxfail=1 --disable-warnings --cov=. --cov-fail-under=100

  build:
    needs: [lint_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/fastapi/Dockerfile
          tags: local/portfolio-api:latest
          push: false

      - name: Build WEB (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/reflex/Dockerfile
          tags: local/portfolio-web:latest
          push: false

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: [self-hosted, portfolio-prod]   # ← 러너 레이블과 일치
    environment:
      name: production
      url: https://joohoonkim.kro.kr
    steps:
      - uses: actions/checkout@v4

      - name: Create env file
        run: |
          cat > .env.prod <<'EOF'
          DB_URL=${{ secrets.DB_URL }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          REFLEX_ENV=prod
          EOF

      - name: Compose build & up (Rocky 서버에서 수행)
        run: |
          docker compose -p portfolio build
          docker compose -p portfolio up -d --remove-orphans

      - name: Health check
        run: |
          curl -fsS https://joohoonkim.kro.kr/ || (docker compose logs --no-color && false)
